include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [lib/**.g.dart]

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    todo: info

linter:
  rules:
    # Bottle Rocket
    - prefer_single_quotes
    - require_trailing_commas
    - always_declare_return_types
    - always_use_package_imports
    - avoid_print

    # I've added a few linter rules that I think would help keep our codebase clean
    # We can adjust these depending on whether we feel they are helping or hurting more
    # I've tried to keep them fairly limited because people tend to dislike heavy usage 
    # A full list of lint rules can be found here: https://dart-lang.github.io/linter/lints/
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - avoid_init_to_null
    - prefer_initializing_formals
    - type_init_formals
    - use_rethrow_when_possible
    - avoid_types_on_closure_parameters
    - avoid_positional_boolean_parameters